### ISSUE TITLE
👑 [需求] 解析插画

### ISSUE THREAD

**Issue by arvinxx** [ant-design/html2sketch#10]
### 🥰 需求描述

能够解析例如下图的插画：

![](https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg)

**Comment by janily** [comment]
蛮好用的，现在是不是还不能解析 background-image 属性引入的背景图片啊

**Comment by arvinxx** [comment]
#20 已实现
