### ISSUE TITLE
🐛[BUG] Checkbox 解析不正确

### ISSUE THREAD

**Issue by arvinxx** [ant-design/html2sketch#12]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/28616219/92332579-8a656580-f0b1-11ea-8070-a48da064085f.png)

![image](https://user-images.githubusercontent.com/28616219/92332592-9a7d4500-f0b1-11ea-8f78-57b967284b57.png)

**Comment by snakeUni** [comment]
除了伪元素，Input 的  placeholder 现在也是支持的嘛。html-sketchapp 不支持 placeholder, 需要单独进行处理。

**Comment by arvinxx** [comment]
#30 已支持
