### ISSUE TITLE
🧐[问题] 可能需要重新配一下 gh-pages

### ISSUE THREAD

**Issue by arvinxx** [ant-design/html2sketch#36]
### 🧐 问题描述

好像跑 deploy 的时候把 gh-pages 删掉了 ，导致现在 [github pages](https://ant-design.github.io/html2sketch/) 显示不出来了😥  @afc163 能不能看下，重新配置下 Github Pages 到 gh-pages 分支？

**Comment by afc163** [comment]
好了。https://github.com/ant-design/html2sketch/settings
