### ISSUE TITLE
🐛[BUG] input 使用 placeholder 或者是 value 显示值时，text-align 样式不生效

### ISSUE THREAD

**Issue by janily** [ant-design/html2sketch#39]
### 🐛 bug 描述

在网页中当  input 标签是使用 placeholder 或者是 value 显示默认值的时候，input 的 text-align 样式在解析生成 sketch 资源的时候不生效。

### 📷 复现步骤

步骤如上描述所示。

解析截图：

![image](https://user-images.githubusercontent.com/1013557/94254156-f290c400-ff58-11ea-9a3a-0c639044aee3.png)

### 🏞 期望结果

能正确解析样式。

### 💻 复现代码

https://codepen.io/janily/pen/LYNaPgo

### © 版本信息

- html2sketch 版本: [e.g. 1.0.0] 0.4.1
- 浏览器环境 Chrome
- 开发环境 [e.g. mac OS] Mac

**Comment by arvinxx** [comment]
#40 已修复，使用 `0.4.2`
