### ISSUE TITLE
🐛[BUG] 生成 sketch 资源细线渲染问题

### ISSUE THREAD

**Issue by janily** [ant-design/html2sketch#46]
### 📷 复现步骤

使用 html 转 sketch 之后，生成 sketch 资源在样式上有问题，会显示多余的一条非常细的线，如图所示：

![image](https://user-images.githubusercontent.com/1013557/96872000-9bbdd200-14a5-11eb-940d-c5d91f73a76f.png)

### 🏞 期望结果

生成的资源没有线

### 💻 复现代码

使用作者的 microwave 这个表格生成插件在sketch中就可以复现。

### © 版本信息

- html2sketch 版本:0.4.2
- 浏览器环境  
- 开发环境 Mac os sketch 版本 69

### 🚑 其他信息

感觉这个是 sketch 自己的渲染有问题，刚新建了一个矩形，用内阴影模拟了一个单边的边框，也有一根细线。

![image](https://user-images.githubusercontent.com/1013557/96952048-75894800-1520-11eb-9cac-f362fe517b48.png)

**Comment by arvinxx** [comment]
sketch 自身的问题。单边 border 只能使用 innerShow 来模拟，它的渲染方式不正确，我这边无法解决的。
