### ISSUE TITLE
🐛[BUG]input 元素设置 placeholder 默认值，并且设置 line-height 属性垂直居中显示，生成 sketch 资源，没有居中显示

### ISSUE THREAD

**Issue by janily** [ant-design/html2sketch#50]
### 🐛 bug 描述

input 元素设置 placeholder 默认值，并且设置 line-height 属性垂直居中显示，生成 sketch 资源，没有居中显示

### 📷 复现步骤

input 元素设置 placeholder 默认值，并且设置 line-height 属性垂直居中显示，生成 sketch 资源，没有居中显示，如图所示

![image](https://user-images.githubusercontent.com/1013557/98757169-e8daf700-2406-11eb-9a49-8d01c6593566.png)

### 🏞 期望结果

居中显示

### 💻 复现代码

下面 demo 可复现问题

[可复现 demo](https://codesandbox.io/s/optimistic-firefly-f7dy8?file=/src/Demo.tsx)

### © 版本信息

- html2sketch 版本: [0.4.6]
- 浏览器环境
- 开发环境 [sketch 69]

**Comment by arvinxx** [comment]
👌 这个应该容易处理的，这几天修掉
