### ISSUE TITLE
🐛[BUG] 元素 padding 和位置解析渲染问题

### ISSUE THREAD

**Issue by janily** [ant-design/html2sketch#51]
### 🐛 bug 描述

我这里又一个 tab UI 在渲染为 sketch 组件的时候，padding 没有正确解析，并且元素的位置解析也没有正确解析。

这是正常的：

![image](https://user-images.githubusercontent.com/1013557/98762239-30b34b80-2412-11eb-8603-902b33dd0fb3.png)

这是渲染的结果：

![image](https://user-images.githubusercontent.com/1013557/98762282-3f99fe00-2412-11eb-9716-66bebc067caf.png)

### 📷 复现步骤

可以用下面的 demo 来复现

### 💻 复现代码

[可复现 demo](https://codesandbox.io/s/happy-hooks-0xtr1?file=/src/styles.css)

### © 版本信息

- html2sketch 版本: [0.46]
- 浏览器环境
- 开发环境 [sketch 69]

**Comment by arvinxx** [comment]
这个可能是因为之前没对 ul 和 li 做专门的解析优化的关系，我研究下咋优化

**Comment by janily** [comment]
大佬，有空看下这个问题么还有另外一个居中的问题么 😄

**Comment by arvinxx** [comment]
> @arvinxx 大佬，有空看下这个问题么还有另外一个居中的问题么 😄

最近有点忙，我争取这周优化掉吧

**Comment by arvinxx** [comment]
经过测试，发现不是 ul 和 li 的问题，而是基于 html 的文本的对齐方式生成 sketch JSON 的 alignment 导致的。

即原来在网页中设置了 `text-align: right` 的会得到 Sketch Alignment 为 `SketchFormat.TextHorizontalAlignment.Right`，而这个数据传入到 sketch 中则会导致 sketch 中文本位置的解析出错，两者的差别只是修改了 TextAlignment 而已。

测试案例： https://gist.github.com/arvinxx/9ad1cda7ffd8702bd47cf29c1c59aef3
