### ISSUE TITLE
🐛[BUG]伪类配合 border 实现三角箭头渲染 bug

### ISSUE THREAD

**Issue by janily** [ant-design/html2sketch#55]
### 🐛 bug 描述

使用伪类配合 border 属性实现三角箭头渲染有 bug，在 sketch 中不能渲染出来，如下图所示：

正常：

![image](https://user-images.githubusercontent.com/1013557/101275933-a679bf80-37e4-11eb-90d7-ee3778188852.png)

sketch 中，三角箭头渲染不出来：

![image](https://user-images.githubusercontent.com/1013557/101275931-9d88ee00-37e4-11eb-906a-8990595b35b6.png)

### 📷 复现步骤

通过下面的 demo 可以复现。

### 💻 复现代码

[可复现 demo](https://codesandbox.io/s/sad-colden-ugzxd?file=/src/Demo.tsx)

### © 版本信息

- html2sketch 版本: [0.4.6]
- 浏览器环境
- 开发环境 [ mac OS]

**Comment by xusang** [comment]
+1

**Comment by arvinxx** [comment]
这种实现应该转不了。原因是 sketch 不支持
